version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://infrad:password@db:5432/infraddb
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      - db
  db:
    build: ./docker/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infraddb
      POSTGRES_USER: infrad
      POSTGRES_PASSWORD: password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    # command: "sleep 1 && psql -U $POSTGRES_USER -d $POSTGRES_DB -f local.sql -f 1.sql"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/