version: '3'
services:
  db:
    image: postgis/postgis:15-3.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: infraddb
      POSTGRES_USER: louwers
      POSTGRES_PASSWORD: password
